name: deploy-app

on: 
  push:
    branches:
      - main

defaults:
  run:
    working-directory: app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - run: npm install

      - uses: shinyinc/action-aws-cli@v1.2
      - run: aws s3 sync build s3://vinitfirstawsbucket/app
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          AWS_ACCESS_KEY_ID: "AKIAQCT7JYLHLSX7RWEO"
          AWS_SECRET_ACCESS_KEY: "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"
          AWS_DEFAULT_REGION: "us-east-1"
